# Default values for cluster-apps.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

ingress-nginx:
  controller:
    service:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
    config:
      use-proxy-protocol: true
      real-ip-header: proxy_protocol
    ingressClassResource:
      default: true
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        additionalLabels:
          release: cluster-apps

cert-manager:
  installCRDs: true

cert-issuer-prod:
  email: devops@dhis2.org
  server: https://acme-v02.api.letsencrypt.org/directory
  # Unsetting the ingressClass value, in order to use default ingress class.
  ingressClass: ""

kube-prometheus-stack:
  grafana:
    persistence:
      enabled: true
      size: 20Gi
      finalizers:
        - kubernetes.io/pvc-protection
    ingress:
      enabled: true
      hosts:
        - grafana.im.dhis2.org
      annotations:
        cert-manager.io/cluster-issuer: cert-issuer-prod
        ingress.kubernetes.io/ssl-redirect: "true"
      tls:
        - secretName: grafana-im-dhis2-org-tls
          hosts:
            - grafana.im.dhis2.org
    adminUser: admin
    adminPassword: # Leave empty for autogenerated password
    additionalDataSources:
      - name: Loki
        type: loki
        url: http://{{ .Release.Name }}-loki:3100
  prometheus:
    prometheusSpec:
      podMonitorSelectorNilUsesHelmValues: false
      serviceMonitorSelectorNilUsesHelmValues: false

loki:
  loki:
    commonConfig:
      replication_factor: 1
    schemaConfig:
      configs:
        - from: "2024-04-01"
          store: tsdb
          object_store: s3
          schema: v13
          index:
            prefix: loki_index_
            period: 24h
    pattern_ingester:
      enabled: true
    limits_config:
      allow_structured_metadata: true
      volume_enabled: true
    ruler:
      enable_api: true
    auth_enabled: false
  minio:
    enabled: true
    persistence:
      size: 20Gi
  deploymentMode: "SingleBinary<->SimpleScalable"
  singleBinary:
    replicas: 1

promtail:
  config:
    clients:
      - url: http://{{ .Release.Name }}-loki:3100/loki/api/v1/push

    snippets:
      extraScrapeConfigs: |
        - job_name: kubernetes-pods-indexed
          kubernetes_sd_configs:
            - role: pod
          pipeline_stages:
            - docker: {}
          relabel_configs:
            - source_labels: [__meta_kubernetes_namespace]
              target_label: namespace
            - source_labels: [__meta_kubernetes_pod_name]
              target_label: pod
            - source_labels: [__meta_kubernetes_container_name]
              target_label: container
            - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_instance]
              target_label: instance
