# Default values for cluster-apps.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

ingress-nginx:
  controller:
    service:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
    config:
      use-proxy-protocol: true
      real-ip-header: proxy_protocol
    ingressClassResource:
      default: true
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        additionalLabels:
          release: prometheus-stack

cert-manager:
  installCRDs: true

cert-issuer-prod:
  email: andreas@dhis2.org
  server: https://acme-v02.api.letsencrypt.org/directory
  # Unsetting the ingressClass value, in order to use default ingress class.
  ingressClass: ""

kube-prometheus-stack:
  grafana:
    persistence:
      enabled: true
      size: 20Gi
    ingress:
      enabled: true
      hosts:
        - grafana.im.dhis2.org
      annotations:
        cert-manager.io/cluster-issuer: cert-issuer-prod
        ingress.kubernetes.io/ssl-redirect: "true"
      tls:
        - secretName: grafana-im-dhis2-org-tls
          hosts:
            - grafana.im.dhis2.org
    adminUser: admin
    adminPassword: # Leave empty for autogenerated password
  prometheus:
    prometheusSpec:
      podMonitorSelectorNilUsesHelmValues: false
      serviceMonitorSelectorNilUsesHelmValues: false

# values.yaml in the umbrella chart

velero:
  image:
    repository: velero/velero
    tag: v1.14.1

  initContainers:
    - name: velero-plugin-for-aws
      image: velero/velero-plugin-for-aws:v1.10.1
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /target
          name: plugins

  securityContext:
    fsGroup: 65534

  configuration:
    provider: aws

    backupStorageLocation:
      name: default
      provider: aws
      bucket: instance-cluster-test-backup
      prefix: velero/
      config:
        region: eu-central-1

    volumeSnapshotLocation:
      name: default
      provider: aws
      config:
        region: eu-central-1
